networks:
  unklab:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    pull_policy: always
    container_name: uptime-kuma
    restart: unless-stopped
    networks:
      - unklab
    volumes:
      - ./uptime-kuma-data:/app/data
